[package]
name = "shell"
version = "0.1.0"
authors = ["liqingwei <lqw332664203@mail.ustc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

whoami = "1.1.0"
libc = "0.2"
nix = "0.20.0"
ctrlc = "3.1.9"